### ISSUE TITLE
Complexity is O(amount of roles) is bad, shall be O(1)

### ISSUE THREAD

**Issue by donDonald** [ElChupi/express-rbac#1]
Hello guys,
As to me isInRole receives array as parameter and leads to iteration over array. Really bad, amount of roles can be 10 or 100 or what ever(at least in my case). It's performance goal for sure. I consider this as critical issue which prevents me of using express-rbac.

I suggest to change isInRole to receive an object in this complexity shall be O(1)

**Comment by ElChupi** [comment]
Actually, changing IsInRole parameters won't do any good as there will never be much roles being evaluated, and if it does, its a bad design. What needs to be changed is the roles array stored as part of the user's roles (This is where you will have a big amount of roles). A Set would probably be a good idea, you are free to submit a PR if you want to...
